# Generated by Django 4.2.20 on 2025-04-23 08:09

import django.contrib.postgres.indexes
from django.db import migrations, models
import saleor.core.utils.json_serializer


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_metadata', models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('name', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('slug',),
                'permissions': (('manage_channels', 'Manage channels.'),),
                'abstract': False,
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['private_metadata'], name='channel_p_meta_idx'), django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='channel_meta_idx')],
            },
        ),
    ]
