# Generated by Django 3.2.2 on 2021-07-13 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0034_remove_checkout_quantity"),
    ]

    operations = [
    ]
