# Generated by Django 3.0.4 on 2020-04-17 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0081_auto_20200406_0456"),
    ]

    operations = [
    ]
