# Generated by Django 3.2.2 on 2021-07-26 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0113_orderevent_app"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="collection_point_name",
            field=models.CharField(
                blank=True, default=None, editable=False, max_length=255, null=True
            ),
        ),
    ]
