# Generated by Django 1.11.5 on 2018-01-08 14:14

import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
from django.db import migrations, models

import saleor.account.models


class Migration(migrations.Migration):
    dependencies = [("account", "0014_auto_20171129_1004")]

    replaces = [("userprofile", "0016_auto_20180108_0814")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user", name="is_active", field=models.BooleanField(default=True)
        ),
        migrations.AlterField(
            model_name="user", name="is_staff", field=models.BooleanField(default=False)
        ),
    ]
